### ISSUE TITLE
Create TTL field

### ISSUE THREAD

**Issue by aparker-cityworks** [aws/aws-dotnet-session-provider#14]
It would be nice if this provider created a TTL field in the DynamoDB record in the format that is required to set up TTL in DynamoDB. Then expired sessions could be deleted without implementing a scheduled cleanup function with DeleteExpiredSessions.

**Comment by normj** [comment]
That feature was added several years ago to the provider. Here is the commit https://github.com/aws/aws-dotnet-session-provider/commit/5ee13694fe7ea66089ceca7c31f547434aa59efa

Are you seeing a problem with the feature or is it a lack of documentation?

**Comment by aparker-cityworks** [comment]
Oh, cool! I was going off of the web config options listed here https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/dynamodb-session-net-sdk.html.

Reading the comments at the top of https://github.com/aws/aws-dotnet-session-provider/blob/master/src/DynamoDBSessionStateStore.cs was very helpful.  Thanks!
