### ISSUE TITLE
Version conflict between dependency declaration (AWSSDK.DynamoDBv2) and latest AWS SDK .Net

### ISSUE THREAD

**Issue by ia64mail** [aws/aws-dotnet-session-provider#5]
@PavelSafronov 

Hello. I'm using the `AWS.SessionProvider` besides with many other libraries from AWS SDK for .Net. 

Since AWS SDK v.3.3.0 has been released I can't use latest version of `AWS.SessionProvider` anymore due to dependency conflict. 

**AWS SDK for .NET: SessionProvider 3.1.0.2**
Dependencies
AWSSDK.DynamoDBv2 (>= 3.1.0 && < 3.2.0)

Thus version of SessionProvider must be downgraded automaticaly down to 

**AWS SDK for .NET: SessionProvider... 2.3.52**
Dependencies
AWSSDK (>= 2.3.52)

Does it compatible with Core v3.3.0? Could you update dependencies restrictions accordingly?

**Comment by normj** [comment]
Thanks for pointing this out. We'll get a rebuilt version of this library targeting 3.3 version of the SDK.

**Comment by normj** [comment]
I just released version 3.1.1 of the session provider which is now built for the version 3.3.X of the SDK

**Comment by ia64mail** [comment]
Thank you for quick update!
