### ISSUE TITLE
Add option to set DynamoDB read/write capacity mode to On-Demand

### ISSUE THREAD

**Issue by drexler** [aws/aws-dotnet-session-provider#7]
With the newly released option for setting DynamoDB read/write capacity to scale with demand - https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing - it will be awesome if this is updated to provide support for it. I can issue a PR for this bandwidth permitting.

**Comment by ashishdhingra** [comment]
This has been released in [AWS.SessionProvider version 4.1.1](https://www.nuget.org/packages/AWS.SessionProvider/4.1.1)
