### ISSUE TITLE
.NET Standard Compatibility?

### ISSUE THREAD

**Issue by dhrivnak** [aws/aws-dotnet-session-provider#9]
I'm sorry if this is the wrong place to ask about future work, but are there any plans to migrate this project to .NET Standard so that those of us using .NET Core can use this project?

Thank you!

**Comment by normj** [comment]
Its not currently planned to make an ASP.NET Core version but if there is significant interest we can definitely look into it. I recommend anybody who would want this feature to chime in to help prioritize this feature request.

**Comment by mario-d-s** [comment]
We would be interested in this as well. A decent starter of an implementation is currently floating on StackOverflow: https://stackoverflow.com/a/52752984/1313143

**Comment by afrowuk** [comment]
I would definitely be interested.

**Comment by normj** [comment]
We are working on a DynamoDB ASP.NET Core `IDistributedCache` provider. For ASP.NET Core the distributed cache framework is the backend store for session state. Here is the repository for that work. We are finishing up internal review work and then we will release the library to NuGet. https://github.com/awslabs/aws-dotnet-distributed-cache-provider

**Comment by ashovlin** [comment]
We've finished all of the internal launch preparation, and just pushed the initial preview version of an `IDistributedCache` provider as https://www.nuget.org/packages/AWS.AspNetCore.DistributedCacheProvider/. As @normj linked above, given the evolution from `SessionStateStoreProviderBase` in .NET Framework to `IDistributedCache` in .NET Core, we've created a separate repository and package.

Here's the launch blog post with some more examples: https://aws.amazon.com/blogs/developer/introducing-the-aws-net-distributed-cache-provider-for-dynamodb-preview/

Let us know what you think via issues and/or pull requests over on the new repo!
